### ISSUE TITLE
Erro creating missions and questions for the galaxy

### ISSUE THREAD

**Issue by JDavidxxx** [tairea/galaxy-maps-v2#108] opened 2024-02-15 21:25 UTC
I create a galaxy perfectly, with the name, the image and the description, but once i created it it wasnt anything else i could do with it, no option apper on the screen.

![Captura de pantalla 2024-02-15 a la(s) 4 24 04 p  m](https://github.com/tairea/galaxy-maps-v2/assets/160152973/4590b878-62ba-4832-822a-a30ebbc5dad6)

**Comment by charsleysa** [comment] 2024-02-15 21:37
Duplicate of #103

**Closed by charsleysa** 2024-02-15 21:37 UTC
